version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
      - ./services:/var/www/html/services
      - ./database:/var/www/html/database
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - my_network

  cli:
    build:
      context: .
      dockerfile: cli/Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    command: php /var/www/html/cli/cli.php
    restart: "no"
    networks:
      - my_network
    stdin_open: true
    tty: true

  frontend:
    build:
      context: .
      dockerfile: next/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./next:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - my_network

networks:
  my_network:
    driver: bridge